package com.dpardo.strike.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import java.io.Serializable;
import java.util.Objects;

/**
 * Representa la Clave Primaria Compuesta (CPK) de la tabla 'session'.
 *
 * Implementa Serializable y los métodos equals() y hashCode().
 */
@Embeddable
public class SessionId implements Serializable {

    /**
     * Esta es la parte de la clave que SÍ es generada por la BD.
     * Mapea 'id_session' (GENERATED BY DEFAULT AS IDENTITY).
     */
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_session", nullable = false)
    private Integer idSession;

    /**
     * Esta es la parte de la clave que es una Clave Foránea.
     * El valor de este campo será "mapeado" desde la
     * relación @ManyToOne en la entidad Session.
     */
    @Column(name = "id_user", nullable = false)
    private Integer idUser; // Mapea a la FK id_user

    // --- Constructor, equals y hashCode (Obligatorios) ---

    public SessionId() {
    }

    public SessionId(Integer idUser) {
        this.idUser = idUser;
    }

    // --- Getters y Setters ---

    public Integer getIdSession() {
        return idSession;
    }

    public void setIdSession(Integer idSession) {
        this.idSession = idSession;
    }

    public Integer getIdUser() {
        return idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    // --- equals() y hashCode() ---

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SessionId sessionId = (SessionId) o;
        return Objects.equals(idSession, sessionId.idSession) &&
                Objects.equals(idUser, sessionId.idUser);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idSession, idUser);
    }
}